from mmmmcoffee/nimplant:0.0.6
#ENV PATH="${PATH}:/root/.nimble/bin:$PATH"
#ENTRYPOINT ["/Mythic/mythic/payload_service.sh"]
#from itsafeaturemythic/python38_payload:0.1.2
#run apt update && apt install -y mingw-w64
#ENTRYPOINT ["/bin/bash"]
#docker run -it nimplantbuild
#RUN curl https://nim-lang.org/choosenim/init.sh -sSf | sh 
#RUN nimble install -y winim 
#RUN nimble install -y nimcrypto
#ENV PATH="${PATH}:/root/.nimble/bin:$PATH"
#ENTRYPOINT ["/Mythic/mythic/payload_service.sh"]

#from mmmmcoffee/nimplant:0.0.3
#ENV PATH="${PATH}:/root/.nimble/bin:$PATH"
#RUN nimble install -y nimcrypto
#run apt update && apt install -y mingw-w64
